/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TitrationRouteImport } from './routes/titration'
import { Route as ThermoRouteImport } from './routes/thermo'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as TableGameRouteImport } from './routes/table-game'
import { Route as StudyRouteImport } from './routes/study'
import { Route as StatesRouteImport } from './routes/states'
import { Route as StartersRouteImport } from './routes/starters'
import { Route as SolutionsRouteImport } from './routes/solutions'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ShopRouteImport } from './routes/shop'
import { Route as ScavengerRouteImport } from './routes/scavenger'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as ReactionsRouteImport } from './routes/reactions'
import { Route as RatesRouteImport } from './routes/rates'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PeriodicTableRouteImport } from './routes/periodic-table'
import { Route as MoleculesRouteImport } from './routes/molecules'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LeaderboardRouteImport } from './routes/leaderboard'
import { Route as LabSafetyRouteImport } from './routes/lab-safety'
import { Route as GrimoireRouteImport } from './routes/grimoire'
import { Route as GasLawsRouteImport } from './routes/gas-laws'
import { Route as ForcesRouteImport } from './routes/forces'
import { Route as EquilibriumRouteImport } from './routes/equilibrium'
import { Route as EquationBalancerRouteImport } from './routes/equation-balancer'
import { Route as ElementsRouteImport } from './routes/elements'
import { Route as ElectroRouteImport } from './routes/electro'
import { Route as DuelsRouteImport } from './routes/duels'
import { Route as DuelRouteImport } from './routes/duel'
import { Route as DecayRouteImport } from './routes/decay'
import { Route as CodexRouteImport } from './routes/codex'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as AtomicBuilderRouteImport } from './routes/atomic-builder'
import { Route as AssignmentsRouteImport } from './routes/assignments'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TitrationRoute = TitrationRouteImport.update({
  id: '/titration',
  path: '/titration',
  getParentRoute: () => rootRouteImport,
} as any)
const ThermoRoute = ThermoRouteImport.update({
  id: '/thermo',
  path: '/thermo',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const TableGameRoute = TableGameRouteImport.update({
  id: '/table-game',
  path: '/table-game',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const StatesRoute = StatesRouteImport.update({
  id: '/states',
  path: '/states',
  getParentRoute: () => rootRouteImport,
} as any)
const StartersRoute = StartersRouteImport.update({
  id: '/starters',
  path: '/starters',
  getParentRoute: () => rootRouteImport,
} as any)
const SolutionsRoute = SolutionsRouteImport.update({
  id: '/solutions',
  path: '/solutions',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ShopRoute = ShopRouteImport.update({
  id: '/shop',
  path: '/shop',
  getParentRoute: () => rootRouteImport,
} as any)
const ScavengerRoute = ScavengerRouteImport.update({
  id: '/scavenger',
  path: '/scavenger',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactionsRoute = ReactionsRouteImport.update({
  id: '/reactions',
  path: '/reactions',
  getParentRoute: () => rootRouteImport,
} as any)
const RatesRoute = RatesRouteImport.update({
  id: '/rates',
  path: '/rates',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PeriodicTableRoute = PeriodicTableRouteImport.update({
  id: '/periodic-table',
  path: '/periodic-table',
  getParentRoute: () => rootRouteImport,
} as any)
const MoleculesRoute = MoleculesRouteImport.update({
  id: '/molecules',
  path: '/molecules',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LeaderboardRoute = LeaderboardRouteImport.update({
  id: '/leaderboard',
  path: '/leaderboard',
  getParentRoute: () => rootRouteImport,
} as any)
const LabSafetyRoute = LabSafetyRouteImport.update({
  id: '/lab-safety',
  path: '/lab-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const GrimoireRoute = GrimoireRouteImport.update({
  id: '/grimoire',
  path: '/grimoire',
  getParentRoute: () => rootRouteImport,
} as any)
const GasLawsRoute = GasLawsRouteImport.update({
  id: '/gas-laws',
  path: '/gas-laws',
  getParentRoute: () => rootRouteImport,
} as any)
const ForcesRoute = ForcesRouteImport.update({
  id: '/forces',
  path: '/forces',
  getParentRoute: () => rootRouteImport,
} as any)
const EquilibriumRoute = EquilibriumRouteImport.update({
  id: '/equilibrium',
  path: '/equilibrium',
  getParentRoute: () => rootRouteImport,
} as any)
const EquationBalancerRoute = EquationBalancerRouteImport.update({
  id: '/equation-balancer',
  path: '/equation-balancer',
  getParentRoute: () => rootRouteImport,
} as any)
const ElementsRoute = ElementsRouteImport.update({
  id: '/elements',
  path: '/elements',
  getParentRoute: () => rootRouteImport,
} as any)
const ElectroRoute = ElectroRouteImport.update({
  id: '/electro',
  path: '/electro',
  getParentRoute: () => rootRouteImport,
} as any)
const DuelsRoute = DuelsRouteImport.update({
  id: '/duels',
  path: '/duels',
  getParentRoute: () => rootRouteImport,
} as any)
const DuelRoute = DuelRouteImport.update({
  id: '/duel',
  path: '/duel',
  getParentRoute: () => rootRouteImport,
} as any)
const DecayRoute = DecayRouteImport.update({
  id: '/decay',
  path: '/decay',
  getParentRoute: () => rootRouteImport,
} as any)
const CodexRoute = CodexRouteImport.update({
  id: '/codex',
  path: '/codex',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AtomicBuilderRoute = AtomicBuilderRouteImport.update({
  id: '/atomic-builder',
  path: '/atomic-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AssignmentsRoute = AssignmentsRouteImport.update({
  id: '/assignments',
  path: '/assignments',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/assignments': typeof AssignmentsRoute
  '/atomic-builder': typeof AtomicBuilderRoute
  '/cards': typeof CardsRoute
  '/codex': typeof CodexRoute
  '/decay': typeof DecayRoute
  '/duel': typeof DuelRoute
  '/duels': typeof DuelsRoute
  '/electro': typeof ElectroRoute
  '/elements': typeof ElementsRoute
  '/equation-balancer': typeof EquationBalancerRoute
  '/equilibrium': typeof EquilibriumRoute
  '/forces': typeof ForcesRoute
  '/gas-laws': typeof GasLawsRoute
  '/grimoire': typeof GrimoireRoute
  '/lab-safety': typeof LabSafetyRoute
  '/leaderboard': typeof LeaderboardRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/molecules': typeof MoleculesRoute
  '/periodic-table': typeof PeriodicTableRoute
  '/quiz': typeof QuizRoute
  '/rates': typeof RatesRoute
  '/reactions': typeof ReactionsRoute
  '/scanner': typeof ScannerRoute
  '/scavenger': typeof ScavengerRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/starters': typeof StartersRoute
  '/states': typeof StatesRoute
  '/study': typeof StudyRoute
  '/table-game': typeof TableGameRoute
  '/teacher': typeof TeacherRoute
  '/thermo': typeof ThermoRoute
  '/titration': typeof TitrationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/assignments': typeof AssignmentsRoute
  '/atomic-builder': typeof AtomicBuilderRoute
  '/cards': typeof CardsRoute
  '/codex': typeof CodexRoute
  '/decay': typeof DecayRoute
  '/duel': typeof DuelRoute
  '/duels': typeof DuelsRoute
  '/electro': typeof ElectroRoute
  '/elements': typeof ElementsRoute
  '/equation-balancer': typeof EquationBalancerRoute
  '/equilibrium': typeof EquilibriumRoute
  '/forces': typeof ForcesRoute
  '/gas-laws': typeof GasLawsRoute
  '/grimoire': typeof GrimoireRoute
  '/lab-safety': typeof LabSafetyRoute
  '/leaderboard': typeof LeaderboardRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/molecules': typeof MoleculesRoute
  '/periodic-table': typeof PeriodicTableRoute
  '/quiz': typeof QuizRoute
  '/rates': typeof RatesRoute
  '/reactions': typeof ReactionsRoute
  '/scanner': typeof ScannerRoute
  '/scavenger': typeof ScavengerRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/starters': typeof StartersRoute
  '/states': typeof StatesRoute
  '/study': typeof StudyRoute
  '/table-game': typeof TableGameRoute
  '/teacher': typeof TeacherRoute
  '/thermo': typeof ThermoRoute
  '/titration': typeof TitrationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/assignments': typeof AssignmentsRoute
  '/atomic-builder': typeof AtomicBuilderRoute
  '/cards': typeof CardsRoute
  '/codex': typeof CodexRoute
  '/decay': typeof DecayRoute
  '/duel': typeof DuelRoute
  '/duels': typeof DuelsRoute
  '/electro': typeof ElectroRoute
  '/elements': typeof ElementsRoute
  '/equation-balancer': typeof EquationBalancerRoute
  '/equilibrium': typeof EquilibriumRoute
  '/forces': typeof ForcesRoute
  '/gas-laws': typeof GasLawsRoute
  '/grimoire': typeof GrimoireRoute
  '/lab-safety': typeof LabSafetyRoute
  '/leaderboard': typeof LeaderboardRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/molecules': typeof MoleculesRoute
  '/periodic-table': typeof PeriodicTableRoute
  '/quiz': typeof QuizRoute
  '/rates': typeof RatesRoute
  '/reactions': typeof ReactionsRoute
  '/scanner': typeof ScannerRoute
  '/scavenger': typeof ScavengerRoute
  '/shop': typeof ShopRoute
  '/signup': typeof SignupRoute
  '/solutions': typeof SolutionsRoute
  '/starters': typeof StartersRoute
  '/states': typeof StatesRoute
  '/study': typeof StudyRoute
  '/table-game': typeof TableGameRoute
  '/teacher': typeof TeacherRoute
  '/thermo': typeof ThermoRoute
  '/titration': typeof TitrationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/assignments'
    | '/atomic-builder'
    | '/cards'
    | '/codex'
    | '/decay'
    | '/duel'
    | '/duels'
    | '/electro'
    | '/elements'
    | '/equation-balancer'
    | '/equilibrium'
    | '/forces'
    | '/gas-laws'
    | '/grimoire'
    | '/lab-safety'
    | '/leaderboard'
    | '/learn'
    | '/login'
    | '/molecules'
    | '/periodic-table'
    | '/quiz'
    | '/rates'
    | '/reactions'
    | '/scanner'
    | '/scavenger'
    | '/shop'
    | '/signup'
    | '/solutions'
    | '/starters'
    | '/states'
    | '/study'
    | '/table-game'
    | '/teacher'
    | '/thermo'
    | '/titration'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/assignments'
    | '/atomic-builder'
    | '/cards'
    | '/codex'
    | '/decay'
    | '/duel'
    | '/duels'
    | '/electro'
    | '/elements'
    | '/equation-balancer'
    | '/equilibrium'
    | '/forces'
    | '/gas-laws'
    | '/grimoire'
    | '/lab-safety'
    | '/leaderboard'
    | '/learn'
    | '/login'
    | '/molecules'
    | '/periodic-table'
    | '/quiz'
    | '/rates'
    | '/reactions'
    | '/scanner'
    | '/scavenger'
    | '/shop'
    | '/signup'
    | '/solutions'
    | '/starters'
    | '/states'
    | '/study'
    | '/table-game'
    | '/teacher'
    | '/thermo'
    | '/titration'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/assignments'
    | '/atomic-builder'
    | '/cards'
    | '/codex'
    | '/decay'
    | '/duel'
    | '/duels'
    | '/electro'
    | '/elements'
    | '/equation-balancer'
    | '/equilibrium'
    | '/forces'
    | '/gas-laws'
    | '/grimoire'
    | '/lab-safety'
    | '/leaderboard'
    | '/learn'
    | '/login'
    | '/molecules'
    | '/periodic-table'
    | '/quiz'
    | '/rates'
    | '/reactions'
    | '/scanner'
    | '/scavenger'
    | '/shop'
    | '/signup'
    | '/solutions'
    | '/starters'
    | '/states'
    | '/study'
    | '/table-game'
    | '/teacher'
    | '/thermo'
    | '/titration'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRoute
  AssignmentsRoute: typeof AssignmentsRoute
  AtomicBuilderRoute: typeof AtomicBuilderRoute
  CardsRoute: typeof CardsRoute
  CodexRoute: typeof CodexRoute
  DecayRoute: typeof DecayRoute
  DuelRoute: typeof DuelRoute
  DuelsRoute: typeof DuelsRoute
  ElectroRoute: typeof ElectroRoute
  ElementsRoute: typeof ElementsRoute
  EquationBalancerRoute: typeof EquationBalancerRoute
  EquilibriumRoute: typeof EquilibriumRoute
  ForcesRoute: typeof ForcesRoute
  GasLawsRoute: typeof GasLawsRoute
  GrimoireRoute: typeof GrimoireRoute
  LabSafetyRoute: typeof LabSafetyRoute
  LeaderboardRoute: typeof LeaderboardRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
  MoleculesRoute: typeof MoleculesRoute
  PeriodicTableRoute: typeof PeriodicTableRoute
  QuizRoute: typeof QuizRoute
  RatesRoute: typeof RatesRoute
  ReactionsRoute: typeof ReactionsRoute
  ScannerRoute: typeof ScannerRoute
  ScavengerRoute: typeof ScavengerRoute
  ShopRoute: typeof ShopRoute
  SignupRoute: typeof SignupRoute
  SolutionsRoute: typeof SolutionsRoute
  StartersRoute: typeof StartersRoute
  StatesRoute: typeof StatesRoute
  StudyRoute: typeof StudyRoute
  TableGameRoute: typeof TableGameRoute
  TeacherRoute: typeof TeacherRoute
  ThermoRoute: typeof ThermoRoute
  TitrationRoute: typeof TitrationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/titration': {
      id: '/titration'
      path: '/titration'
      fullPath: '/titration'
      preLoaderRoute: typeof TitrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/thermo': {
      id: '/thermo'
      path: '/thermo'
      fullPath: '/thermo'
      preLoaderRoute: typeof ThermoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/table-game': {
      id: '/table-game'
      path: '/table-game'
      fullPath: '/table-game'
      preLoaderRoute: typeof TableGameRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/states': {
      id: '/states'
      path: '/states'
      fullPath: '/states'
      preLoaderRoute: typeof StatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/starters': {
      id: '/starters'
      path: '/starters'
      fullPath: '/starters'
      preLoaderRoute: typeof StartersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/solutions': {
      id: '/solutions'
      path: '/solutions'
      fullPath: '/solutions'
      preLoaderRoute: typeof SolutionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shop': {
      id: '/shop'
      path: '/shop'
      fullPath: '/shop'
      preLoaderRoute: typeof ShopRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scavenger': {
      id: '/scavenger'
      path: '/scavenger'
      fullPath: '/scavenger'
      preLoaderRoute: typeof ScavengerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reactions': {
      id: '/reactions'
      path: '/reactions'
      fullPath: '/reactions'
      preLoaderRoute: typeof ReactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rates': {
      id: '/rates'
      path: '/rates'
      fullPath: '/rates'
      preLoaderRoute: typeof RatesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/periodic-table': {
      id: '/periodic-table'
      path: '/periodic-table'
      fullPath: '/periodic-table'
      preLoaderRoute: typeof PeriodicTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/molecules': {
      id: '/molecules'
      path: '/molecules'
      fullPath: '/molecules'
      preLoaderRoute: typeof MoleculesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/leaderboard': {
      id: '/leaderboard'
      path: '/leaderboard'
      fullPath: '/leaderboard'
      preLoaderRoute: typeof LeaderboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab-safety': {
      id: '/lab-safety'
      path: '/lab-safety'
      fullPath: '/lab-safety'
      preLoaderRoute: typeof LabSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grimoire': {
      id: '/grimoire'
      path: '/grimoire'
      fullPath: '/grimoire'
      preLoaderRoute: typeof GrimoireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gas-laws': {
      id: '/gas-laws'
      path: '/gas-laws'
      fullPath: '/gas-laws'
      preLoaderRoute: typeof GasLawsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forces': {
      id: '/forces'
      path: '/forces'
      fullPath: '/forces'
      preLoaderRoute: typeof ForcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equilibrium': {
      id: '/equilibrium'
      path: '/equilibrium'
      fullPath: '/equilibrium'
      preLoaderRoute: typeof EquilibriumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equation-balancer': {
      id: '/equation-balancer'
      path: '/equation-balancer'
      fullPath: '/equation-balancer'
      preLoaderRoute: typeof EquationBalancerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elements': {
      id: '/elements'
      path: '/elements'
      fullPath: '/elements'
      preLoaderRoute: typeof ElementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/electro': {
      id: '/electro'
      path: '/electro'
      fullPath: '/electro'
      preLoaderRoute: typeof ElectroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duels': {
      id: '/duels'
      path: '/duels'
      fullPath: '/duels'
      preLoaderRoute: typeof DuelsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/duel': {
      id: '/duel'
      path: '/duel'
      fullPath: '/duel'
      preLoaderRoute: typeof DuelRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decay': {
      id: '/decay'
      path: '/decay'
      fullPath: '/decay'
      preLoaderRoute: typeof DecayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/codex': {
      id: '/codex'
      path: '/codex'
      fullPath: '/codex'
      preLoaderRoute: typeof CodexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atomic-builder': {
      id: '/atomic-builder'
      path: '/atomic-builder'
      fullPath: '/atomic-builder'
      preLoaderRoute: typeof AtomicBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/assignments': {
      id: '/assignments'
      path: '/assignments'
      fullPath: '/assignments'
      preLoaderRoute: typeof AssignmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRoute,
  AssignmentsRoute: AssignmentsRoute,
  AtomicBuilderRoute: AtomicBuilderRoute,
  CardsRoute: CardsRoute,
  CodexRoute: CodexRoute,
  DecayRoute: DecayRoute,
  DuelRoute: DuelRoute,
  DuelsRoute: DuelsRoute,
  ElectroRoute: ElectroRoute,
  ElementsRoute: ElementsRoute,
  EquationBalancerRoute: EquationBalancerRoute,
  EquilibriumRoute: EquilibriumRoute,
  ForcesRoute: ForcesRoute,
  GasLawsRoute: GasLawsRoute,
  GrimoireRoute: GrimoireRoute,
  LabSafetyRoute: LabSafetyRoute,
  LeaderboardRoute: LeaderboardRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
  MoleculesRoute: MoleculesRoute,
  PeriodicTableRoute: PeriodicTableRoute,
  QuizRoute: QuizRoute,
  RatesRoute: RatesRoute,
  ReactionsRoute: ReactionsRoute,
  ScannerRoute: ScannerRoute,
  ScavengerRoute: ScavengerRoute,
  ShopRoute: ShopRoute,
  SignupRoute: SignupRoute,
  SolutionsRoute: SolutionsRoute,
  StartersRoute: StartersRoute,
  StatesRoute: StatesRoute,
  StudyRoute: StudyRoute,
  TableGameRoute: TableGameRoute,
  TeacherRoute: TeacherRoute,
  ThermoRoute: ThermoRoute,
  TitrationRoute: TitrationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
