/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TitrationRouteImport } from './routes/titration'
import { Route as TeacherRouteImport } from './routes/teacher'
import { Route as StudyRouteImport } from './routes/study'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ScavengerRouteImport } from './routes/scavenger'
import { Route as ScannerRouteImport } from './routes/scanner'
import { Route as ReactionsRouteImport } from './routes/reactions'
import { Route as QuizRouteImport } from './routes/quiz'
import { Route as PeriodicTableRouteImport } from './routes/periodic-table'
import { Route as MoleculesRouteImport } from './routes/molecules'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LearnRouteImport } from './routes/learn'
import { Route as LabSafetyRouteImport } from './routes/lab-safety'
import { Route as GrimoireRouteImport } from './routes/grimoire'
import { Route as GasLawsRouteImport } from './routes/gas-laws'
import { Route as EquationBalancerRouteImport } from './routes/equation-balancer'
import { Route as ElementsRouteImport } from './routes/elements'
import { Route as DecayRouteImport } from './routes/decay'
import { Route as CardsRouteImport } from './routes/cards'
import { Route as AtomicBuilderRouteImport } from './routes/atomic-builder'
import { Route as AppRouteImport } from './routes/app'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TitrationRoute = TitrationRouteImport.update({
  id: '/titration',
  path: '/titration',
  getParentRoute: () => rootRouteImport,
} as any)
const TeacherRoute = TeacherRouteImport.update({
  id: '/teacher',
  path: '/teacher',
  getParentRoute: () => rootRouteImport,
} as any)
const StudyRoute = StudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ScavengerRoute = ScavengerRouteImport.update({
  id: '/scavenger',
  path: '/scavenger',
  getParentRoute: () => rootRouteImport,
} as any)
const ScannerRoute = ScannerRouteImport.update({
  id: '/scanner',
  path: '/scanner',
  getParentRoute: () => rootRouteImport,
} as any)
const ReactionsRoute = ReactionsRouteImport.update({
  id: '/reactions',
  path: '/reactions',
  getParentRoute: () => rootRouteImport,
} as any)
const QuizRoute = QuizRouteImport.update({
  id: '/quiz',
  path: '/quiz',
  getParentRoute: () => rootRouteImport,
} as any)
const PeriodicTableRoute = PeriodicTableRouteImport.update({
  id: '/periodic-table',
  path: '/periodic-table',
  getParentRoute: () => rootRouteImport,
} as any)
const MoleculesRoute = MoleculesRouteImport.update({
  id: '/molecules',
  path: '/molecules',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LearnRoute = LearnRouteImport.update({
  id: '/learn',
  path: '/learn',
  getParentRoute: () => rootRouteImport,
} as any)
const LabSafetyRoute = LabSafetyRouteImport.update({
  id: '/lab-safety',
  path: '/lab-safety',
  getParentRoute: () => rootRouteImport,
} as any)
const GrimoireRoute = GrimoireRouteImport.update({
  id: '/grimoire',
  path: '/grimoire',
  getParentRoute: () => rootRouteImport,
} as any)
const GasLawsRoute = GasLawsRouteImport.update({
  id: '/gas-laws',
  path: '/gas-laws',
  getParentRoute: () => rootRouteImport,
} as any)
const EquationBalancerRoute = EquationBalancerRouteImport.update({
  id: '/equation-balancer',
  path: '/equation-balancer',
  getParentRoute: () => rootRouteImport,
} as any)
const ElementsRoute = ElementsRouteImport.update({
  id: '/elements',
  path: '/elements',
  getParentRoute: () => rootRouteImport,
} as any)
const DecayRoute = DecayRouteImport.update({
  id: '/decay',
  path: '/decay',
  getParentRoute: () => rootRouteImport,
} as any)
const CardsRoute = CardsRouteImport.update({
  id: '/cards',
  path: '/cards',
  getParentRoute: () => rootRouteImport,
} as any)
const AtomicBuilderRoute = AtomicBuilderRouteImport.update({
  id: '/atomic-builder',
  path: '/atomic-builder',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/atomic-builder': typeof AtomicBuilderRoute
  '/cards': typeof CardsRoute
  '/decay': typeof DecayRoute
  '/elements': typeof ElementsRoute
  '/equation-balancer': typeof EquationBalancerRoute
  '/gas-laws': typeof GasLawsRoute
  '/grimoire': typeof GrimoireRoute
  '/lab-safety': typeof LabSafetyRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/molecules': typeof MoleculesRoute
  '/periodic-table': typeof PeriodicTableRoute
  '/quiz': typeof QuizRoute
  '/reactions': typeof ReactionsRoute
  '/scanner': typeof ScannerRoute
  '/scavenger': typeof ScavengerRoute
  '/signup': typeof SignupRoute
  '/study': typeof StudyRoute
  '/teacher': typeof TeacherRoute
  '/titration': typeof TitrationRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/atomic-builder': typeof AtomicBuilderRoute
  '/cards': typeof CardsRoute
  '/decay': typeof DecayRoute
  '/elements': typeof ElementsRoute
  '/equation-balancer': typeof EquationBalancerRoute
  '/gas-laws': typeof GasLawsRoute
  '/grimoire': typeof GrimoireRoute
  '/lab-safety': typeof LabSafetyRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/molecules': typeof MoleculesRoute
  '/periodic-table': typeof PeriodicTableRoute
  '/quiz': typeof QuizRoute
  '/reactions': typeof ReactionsRoute
  '/scanner': typeof ScannerRoute
  '/scavenger': typeof ScavengerRoute
  '/signup': typeof SignupRoute
  '/study': typeof StudyRoute
  '/teacher': typeof TeacherRoute
  '/titration': typeof TitrationRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/app': typeof AppRoute
  '/atomic-builder': typeof AtomicBuilderRoute
  '/cards': typeof CardsRoute
  '/decay': typeof DecayRoute
  '/elements': typeof ElementsRoute
  '/equation-balancer': typeof EquationBalancerRoute
  '/gas-laws': typeof GasLawsRoute
  '/grimoire': typeof GrimoireRoute
  '/lab-safety': typeof LabSafetyRoute
  '/learn': typeof LearnRoute
  '/login': typeof LoginRoute
  '/molecules': typeof MoleculesRoute
  '/periodic-table': typeof PeriodicTableRoute
  '/quiz': typeof QuizRoute
  '/reactions': typeof ReactionsRoute
  '/scanner': typeof ScannerRoute
  '/scavenger': typeof ScavengerRoute
  '/signup': typeof SignupRoute
  '/study': typeof StudyRoute
  '/teacher': typeof TeacherRoute
  '/titration': typeof TitrationRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/atomic-builder'
    | '/cards'
    | '/decay'
    | '/elements'
    | '/equation-balancer'
    | '/gas-laws'
    | '/grimoire'
    | '/lab-safety'
    | '/learn'
    | '/login'
    | '/molecules'
    | '/periodic-table'
    | '/quiz'
    | '/reactions'
    | '/scanner'
    | '/scavenger'
    | '/signup'
    | '/study'
    | '/teacher'
    | '/titration'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/atomic-builder'
    | '/cards'
    | '/decay'
    | '/elements'
    | '/equation-balancer'
    | '/gas-laws'
    | '/grimoire'
    | '/lab-safety'
    | '/learn'
    | '/login'
    | '/molecules'
    | '/periodic-table'
    | '/quiz'
    | '/reactions'
    | '/scanner'
    | '/scavenger'
    | '/signup'
    | '/study'
    | '/teacher'
    | '/titration'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/app'
    | '/atomic-builder'
    | '/cards'
    | '/decay'
    | '/elements'
    | '/equation-balancer'
    | '/gas-laws'
    | '/grimoire'
    | '/lab-safety'
    | '/learn'
    | '/login'
    | '/molecules'
    | '/periodic-table'
    | '/quiz'
    | '/reactions'
    | '/scanner'
    | '/scavenger'
    | '/signup'
    | '/study'
    | '/teacher'
    | '/titration'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  AppRoute: typeof AppRoute
  AtomicBuilderRoute: typeof AtomicBuilderRoute
  CardsRoute: typeof CardsRoute
  DecayRoute: typeof DecayRoute
  ElementsRoute: typeof ElementsRoute
  EquationBalancerRoute: typeof EquationBalancerRoute
  GasLawsRoute: typeof GasLawsRoute
  GrimoireRoute: typeof GrimoireRoute
  LabSafetyRoute: typeof LabSafetyRoute
  LearnRoute: typeof LearnRoute
  LoginRoute: typeof LoginRoute
  MoleculesRoute: typeof MoleculesRoute
  PeriodicTableRoute: typeof PeriodicTableRoute
  QuizRoute: typeof QuizRoute
  ReactionsRoute: typeof ReactionsRoute
  ScannerRoute: typeof ScannerRoute
  ScavengerRoute: typeof ScavengerRoute
  SignupRoute: typeof SignupRoute
  StudyRoute: typeof StudyRoute
  TeacherRoute: typeof TeacherRoute
  TitrationRoute: typeof TitrationRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/titration': {
      id: '/titration'
      path: '/titration'
      fullPath: '/titration'
      preLoaderRoute: typeof TitrationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/teacher': {
      id: '/teacher'
      path: '/teacher'
      fullPath: '/teacher'
      preLoaderRoute: typeof TeacherRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/study': {
      id: '/study'
      path: '/study'
      fullPath: '/study'
      preLoaderRoute: typeof StudyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scavenger': {
      id: '/scavenger'
      path: '/scavenger'
      fullPath: '/scavenger'
      preLoaderRoute: typeof ScavengerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/scanner': {
      id: '/scanner'
      path: '/scanner'
      fullPath: '/scanner'
      preLoaderRoute: typeof ScannerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reactions': {
      id: '/reactions'
      path: '/reactions'
      fullPath: '/reactions'
      preLoaderRoute: typeof ReactionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quiz': {
      id: '/quiz'
      path: '/quiz'
      fullPath: '/quiz'
      preLoaderRoute: typeof QuizRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/periodic-table': {
      id: '/periodic-table'
      path: '/periodic-table'
      fullPath: '/periodic-table'
      preLoaderRoute: typeof PeriodicTableRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/molecules': {
      id: '/molecules'
      path: '/molecules'
      fullPath: '/molecules'
      preLoaderRoute: typeof MoleculesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/learn': {
      id: '/learn'
      path: '/learn'
      fullPath: '/learn'
      preLoaderRoute: typeof LearnRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lab-safety': {
      id: '/lab-safety'
      path: '/lab-safety'
      fullPath: '/lab-safety'
      preLoaderRoute: typeof LabSafetyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grimoire': {
      id: '/grimoire'
      path: '/grimoire'
      fullPath: '/grimoire'
      preLoaderRoute: typeof GrimoireRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/gas-laws': {
      id: '/gas-laws'
      path: '/gas-laws'
      fullPath: '/gas-laws'
      preLoaderRoute: typeof GasLawsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equation-balancer': {
      id: '/equation-balancer'
      path: '/equation-balancer'
      fullPath: '/equation-balancer'
      preLoaderRoute: typeof EquationBalancerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/elements': {
      id: '/elements'
      path: '/elements'
      fullPath: '/elements'
      preLoaderRoute: typeof ElementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decay': {
      id: '/decay'
      path: '/decay'
      fullPath: '/decay'
      preLoaderRoute: typeof DecayRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cards': {
      id: '/cards'
      path: '/cards'
      fullPath: '/cards'
      preLoaderRoute: typeof CardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/atomic-builder': {
      id: '/atomic-builder'
      path: '/atomic-builder'
      fullPath: '/atomic-builder'
      preLoaderRoute: typeof AtomicBuilderRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  AppRoute: AppRoute,
  AtomicBuilderRoute: AtomicBuilderRoute,
  CardsRoute: CardsRoute,
  DecayRoute: DecayRoute,
  ElementsRoute: ElementsRoute,
  EquationBalancerRoute: EquationBalancerRoute,
  GasLawsRoute: GasLawsRoute,
  GrimoireRoute: GrimoireRoute,
  LabSafetyRoute: LabSafetyRoute,
  LearnRoute: LearnRoute,
  LoginRoute: LoginRoute,
  MoleculesRoute: MoleculesRoute,
  PeriodicTableRoute: PeriodicTableRoute,
  QuizRoute: QuizRoute,
  ReactionsRoute: ReactionsRoute,
  ScannerRoute: ScannerRoute,
  ScavengerRoute: ScavengerRoute,
  SignupRoute: SignupRoute,
  StudyRoute: StudyRoute,
  TeacherRoute: TeacherRoute,
  TitrationRoute: TitrationRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
